export const STANDARD_RESOURCE_IMAGE_SQUARE_SIZE = 400
export const DEFAULT_LOCATION_LAT_LNG = {latitude: 50.6058984, longitude: 3.3881915}
export const DEFAULT_LOCATION = { address: 'Beffroi de Tournai', latitude: 50.6058167, longitude: 3.3880374 }
export const ADD_LOGO_REWARD = 20
export const ADD_LOCATION_REWARD = 20
export const ADD_LINK_REWARD = 20
export const ADD_RESOURCE_PICTURE_REWARD = 5
export const ADD_RESOURCE_PRICE_REWARD = 15
export const CREATE_RESOURCE_REWARD = 20