import Profile from './assets/img/PROFIL.svg'
import Cross from './assets/img/CROSS.svg'
import Arrow from './assets/img/fleche.svg'
import Heart from './assets/img/HEART.svg'
import Received from './assets/img/RECU.svg'
import Sent from './assets/img/ENVOYE.svg'
import Valid from './assets/img/VALID.svg'
import Search from './assets/img/LOUPE.svg'
import Modify from './assets/img/PENCIL.svg'
import Chat from './assets/img/CHAT.svg'
import History from './assets/img/HISTORY.svg'
import Photos from './assets/img/PHOTOS.svg'
import BackgroundChat from './assets/img/background-chat.svg'

export default { Profile, Cross, Arrow, Heart, Received, Sent, Valid, Search, Modify, Chat, History, Photos, BackgroundChat }