version: '2.1'
services:
  sb_web:
    build:
      context: './..'
      dockerfile: './docker/web/Dockerfile'
    ports:
      - "3000:3000"
  sb_proxy:
    build:
      context: './proxy'
    depends_on:
      - sb_web
      - sb_nocodb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/var/local
  sb_nocodb:
    depends_on: 
      sb_db: 
        condition: service_healthy
    env_file:
      - .env
    image: "nocodb/nocodb:0.109.3"
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
      - "nc_data:/usr/app/data"
  sb_db:
    env_file:
      - .env
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres@sha256:31c9342603866f29206a06b77c8fed48b3c3f70d710a4be4e8216b134f92d0df
    restart: always
    volumes: 
      - "db_data:/var/lib/postgresql/data"
  state:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  scheduler:
    depends_on:
      - sb_db
      - state
    build:
      dockerfile: './scheduler/Dockerfile'
    restart: always
volumes: 
  db_data: {}
  nc_data: {}
networks:
  proxynet:
    name: sb_network